### ISSUE TITLE
Consider targeting Erlang or Core Erlang rather than Elixir

### ISSUE THREAD

**Issue by lpil** [jmitchell/idris-elixir#1]
Hello! Nice project, I'd love to see Idris on the BEAM.

I was wondering why you were targeting Elixir here, rather than Erlang or Core Erlang. Here's the current process:

```
Idris -> Elixir -> Erlang AST -> Core Erlang -> BEAM
```

We could have one of these instead:

```
Idris -> Erlang -> Core Erlang -> BEAM
Idris -> Core Erlang -> BEAM
```

There are a few benefits of this:

- Removes the need for the Elixir compiler and runtime, reducing the number of deps required to down to the standard Erlang distibution
- Improves compilation speed by removing the Elixir -> Erlang process
- Simpler code generation. Erlang is a simpler language than Elixir, and Core Erlang even more so. Core Erlang is designed to be a compilation target.
- More stable. Elixir syntax is still evolving and some features and syntaxes are being deprecated and removed. Erlang and Core Erlang do not have this problem.

To me it's unclear what the advantage of targeting Elixir currently is, would be good to get your thoughts. :)

Thank you,
Louis

**Comment by jmitchell** [comment]
Hi Louis, thanks for sharing your thoughts.

There's already an unofficial generator for Erlang [here](https://github.com/lenary/idris-erlang), although I haven't used it. There's also a list of all the backends [here](http://docs.idris-lang.org/en/latest/reference/codegen.html). This project is nowhere near ready for submission to that list.

Although producing BEAM bytecode in the fewest translation stages is a worthwhile goal, it's not a goal for this project. If `idris-erlang` doesn't already support targeting Core Erlang that would be a great project for somebody to tackle.

Honestly, I started this project mostly for fun. Some of my motivations:

* I enjoy both Idris and Elixir, and want to get more familiar with their inner workings.
* I'm curious whether any of Idris' supported intermediate representations leave room for optimizations or perhaps would map well onto new Elixir macros that could improve compile-time guarantees for Elixir users who won't bother with Idris.
* I'd like to concretely show Elixir users how dependent types can obviate several classes of errors that would otherwise be difficult to catch.
* I'm curious whether Edwin Brady's work on dependently typed state machines and protocols could be translated into safer message passing and/or hot code reloading.

Several of these objectives would be possible for Erlang or Core Erlang too, and someday I might contribute to that effort if others haven't/don't beat me to it. I haven't studied Core Erlang's API yet, but another interesting possibility is Elixir and its AST macros may be better positioned to optimize high-level BEAM abstractions. This project could eventually produce smaller/faster BEAM code than a direct Core Erlang backend (although I'm really not banking on it).

I'm going to close this issue, but feel free to share additional thoughts about it here.

**Comment by jmitchell** [comment]
As a quick follow-up, if/when another project produces better BEAM code I will advertise it in the README, suggesting it's a more pragmatic option (unless/until I demonstrate otherwise).

Don't hesitate to let me know if you identify a worthy project.

**Comment by lpil** [comment]
Cool, thanks for your thoughts. All very reasonable :)
